apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: tlsmbl
      app.kubernetes.io/part-of: tlsmbl
      app.kubernetes.io/component: solver
    includeSelectors: false

configMapGenerator:
  - name: tlsmbl-run-config
    files:
      - run.yaml=run-config.yaml

images:
  - name: tls-mbl-peps
    newTag: 0.0.1
